### ISSUE TITLE
(6.1.2) Define the users that would benefit from your website

### ISSUE THREAD

**Issue by Bogdanpoda** [MatthewBeaulieu0/SOEN-343_TheShabbab#2]

**Comment by AgnesCroteau** [comment]
The users benefitting are all ''stakeholders" (parties prenantes)
i.e. if the website is about sports for children 2-4 y.o. then the stakeholders are children, and parents.  
Just commenting because I asked the T.A. about it to be sure.  The context diagram helps as well in this regard.
