### ISSUE TITLE
(6.1.5) what are the advantages and features of your solution in comparison with the existing ones

### ISSUE THREAD

**Issue by Bogdanpoda** [MatthewBeaulieu0/SOEN-343_TheShabbab#7]

**Comment by AgnesCroteau** [comment]
We could say : ''well most don't take into account disabled or older students preferences. Which could make them feel a bit left out of the Uni experience. Our website offers them a few valid options to prevent this from happening."

I hope the rest of the team agrees, let me/us know if anything.

**Comment by Bogdanpoda** [comment]
That is a great idea!
