### ISSUE TITLE
(6.2) Context Diagram

### ISSUE THREAD

**Issue by Bogdanpoda** [MatthewBeaulieu0/SOEN-343_TheShabbab#9]
Phase 1: Context Diagram (6.2)

**Comment by AgnesCroteau** [comment]
https://www.modernanalyst.com/Careers/InterviewQuestions/tabid/128/ID/1433/What-is-a-Context-Diagram-and-what-are-the-benefits-of-creating-one.aspx

**Comment by aspyridakos** [comment]
Reviewed by @aspyridakos for consistency with report and domain model diagram. Great work @jonathan-githubofficial 🚀
